"""Added company security composite table

Revision ID: 73c90a5834af
Revises: fad13d3f9cc8
Create Date: 2018-05-26 14:22:42.707018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73c90a5834af'
down_revision = 'fad13d3f9cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security', sa.Column('share_class_figi', sa.String(length=15), nullable=True))
    op.drop_column('security', 'ShareclassFigi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security', sa.Column('ShareclassFigi', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.drop_column('security', 'share_class_figi')
    # ### end Alembic commands ###
