"""Added company security composite table

Revision ID: cc6b3fe3bbf2
Revises: 73c90a5834af
Create Date: 2018-05-26 14:23:46.450533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc6b3fe3bbf2'
down_revision = '73c90a5834af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security', sa.Column('unique_id_futopt', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('security', 'unique_id_futopt')
    # ### end Alembic commands ###
