"""Added company security composite table

Revision ID: fad13d3f9cc8
Revises: 
Create Date: 2018-05-26 13:39:00.007133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fad13d3f9cc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('cik', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('sic', sa.Integer(), nullable=True),
    sa.Column('gics_sector', sa.String(length=50), nullable=True),
    sa.Column('gics_subindustry', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('founded_year', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('cik')
    )
    op.create_table('security',
    sa.Column('figi', sa.String(length=15), nullable=False),
    sa.Column('market_sector', sa.String(length=20), nullable=True),
    sa.Column('composite_figi', sa.String(length=15), nullable=True),
    sa.Column('ShareclassFigi', sa.String(length=15), nullable=True),
    sa.Column('security_type', sa.String(length=20), nullable=True),
    sa.Column('security_type2', sa.String(length=20), nullable=True),
    sa.Column('unique_id', sa.String(length=20), nullable=True),
    sa.Column('exch_code', sa.String(length=2), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('security_description', sa.String(length=250), nullable=True),
    sa.Column('cik', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cik'], ['company.cik'], onupdate='cascade'),
    sa.PrimaryKeyConstraint('figi')
    )
    op.create_table('composite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=15), nullable=True),
    sa.Column('asof_date', sa.DateTime(), nullable=True),
    sa.Column('figi', sa.String(length=15), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('share', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['figi'], ['security.figi'], onupdate='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('composite')
    op.drop_table('security')
    op.drop_table('company')
    # ### end Alembic commands ###
